#ifndef INCLUDED__apiAOS_SAMPLEPROJECT_HPP__ 
#define INCLUDED__apiAOS_SAMPLEPROJECT_HPP__

#ifdef AOS_SAMPLEPROJECTUPPERCASE_EXPORTS
#define AOS_SAMPLEPROJECTUPPERCASE_API __declspec(dllexport)
#else
#define AOS_SAMPLEPROJECTUPPERCASE_API __declspec(dllimport)
#endif

#endif // INCLUDED__apiAOS_SAMPLEPROJECT_HPP__
